name: Deploy to FTP on merge to main

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest  # Use the official Debian runner (Debian 11)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up git-ftp
        run: |
          sudo apt-get update
          sudo apt-get install -y git-ftp

      # FTP credentials from GitHub secrets
      - name: Set FTP credentials
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          git config --global credential.helper store
          git ftp init -vv ftp.starhotelgrandcanyon.com --user=$FTP_USERNAME --passwd=$FTP_PASSWORD

      # Push changes to FTP server
      - name: Push changes to FTP
        run: git ftp push --ftp-url=ftp.starhotelgrandcanyon.com --user=$FTP_USERNAME --passwd=$FTP_PASSWORD