name: Deploy to FTP on merge to main

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up git-ftp
        run: |
          sudo apt-get update
          sudo apt-get install -y git-ftp

      # - name: Authenticate with FTP
      #   run: |
      #     git config --global credential.helper store
      #     echo "machine ${{ secrets.FTP_SERVER }}" >> ~/.netrc
      #     echo "login ${{ secrets.FTP_USERNAME }}" >> ~/.netrc
      #     echo "password ${{ secrets.FTP_PASSWORD }}" >> ~/.netrc

      - name: Git FTP push
        run: |
          git ftp init $FTP_SERVER --user $FTP_USERNAME --passwd $FTP_PASSWORD
          git ftp push --force $FTP_SERVER --user $FTP_USERNAME --passwd $FTP_PASSWORD
