name: Deploy to FTP on merge to main

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest  # Use the official Debian runner (Debian 11)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up git-ftp
        run: |
          sudo apt-get update
          sudo apt-get install -y git-ftp

      # - name: Authenticate with FTP
      #   run: |
          

      - name: Git FTP push
        run: |
          git config git-ftp.url "ftp.starhotelgrandcanyon.com"
          git config git-ftp.password "$FTP_PASSWORD"
          git ftp init --user $FTP_USERNAME "ftp.starhotelgrandcanyon.com" && git ftp push -f